development:
 adapter: postgresql
 encoding: unicode
 host: localhost
 username: remy
 database: trecarga_development
 pool: 5
 password: one

test:
 adapter: postgresql
 encoding: unicode
 host: localhost
 username: remy
 database: trecarga_test
 pool: 5
 password: one
