require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PlanCuentaController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # PlanCuentum. As you add validations to PlanCuentum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlanCuentaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all plan_cuenta as @plan_cuenta" do
      plan_cuentum = PlanCuentum.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:plan_cuenta)).to eq([plan_cuentum])
    end
  end

  describe "GET show" do
    it "assigns the requested plan_cuentum as @plan_cuentum" do
      plan_cuentum = PlanCuentum.create! valid_attributes
      get :show, {:id => plan_cuentum.to_param}, valid_session
      expect(assigns(:plan_cuentum)).to eq(plan_cuentum)
    end
  end

  describe "GET new" do
    it "assigns a new plan_cuentum as @plan_cuentum" do
      get :new, {}, valid_session
      expect(assigns(:plan_cuentum)).to be_a_new(PlanCuentum)
    end
  end

  describe "GET edit" do
    it "assigns the requested plan_cuentum as @plan_cuentum" do
      plan_cuentum = PlanCuentum.create! valid_attributes
      get :edit, {:id => plan_cuentum.to_param}, valid_session
      expect(assigns(:plan_cuentum)).to eq(plan_cuentum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlanCuentum" do
        expect {
          post :create, {:plan_cuentum => valid_attributes}, valid_session
        }.to change(PlanCuentum, :count).by(1)
      end

      it "assigns a newly created plan_cuentum as @plan_cuentum" do
        post :create, {:plan_cuentum => valid_attributes}, valid_session
        expect(assigns(:plan_cuentum)).to be_a(PlanCuentum)
        expect(assigns(:plan_cuentum)).to be_persisted
      end

      it "redirects to the created plan_cuentum" do
        post :create, {:plan_cuentum => valid_attributes}, valid_session
        expect(response).to redirect_to(PlanCuentum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved plan_cuentum as @plan_cuentum" do
        post :create, {:plan_cuentum => invalid_attributes}, valid_session
        expect(assigns(:plan_cuentum)).to be_a_new(PlanCuentum)
      end

      it "re-renders the 'new' template" do
        post :create, {:plan_cuentum => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested plan_cuentum" do
        plan_cuentum = PlanCuentum.create! valid_attributes
        put :update, {:id => plan_cuentum.to_param, :plan_cuentum => new_attributes}, valid_session
        plan_cuentum.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested plan_cuentum as @plan_cuentum" do
        plan_cuentum = PlanCuentum.create! valid_attributes
        put :update, {:id => plan_cuentum.to_param, :plan_cuentum => valid_attributes}, valid_session
        expect(assigns(:plan_cuentum)).to eq(plan_cuentum)
      end

      it "redirects to the plan_cuentum" do
        plan_cuentum = PlanCuentum.create! valid_attributes
        put :update, {:id => plan_cuentum.to_param, :plan_cuentum => valid_attributes}, valid_session
        expect(response).to redirect_to(plan_cuentum)
      end
    end

    describe "with invalid params" do
      it "assigns the plan_cuentum as @plan_cuentum" do
        plan_cuentum = PlanCuentum.create! valid_attributes
        put :update, {:id => plan_cuentum.to_param, :plan_cuentum => invalid_attributes}, valid_session
        expect(assigns(:plan_cuentum)).to eq(plan_cuentum)
      end

      it "re-renders the 'edit' template" do
        plan_cuentum = PlanCuentum.create! valid_attributes
        put :update, {:id => plan_cuentum.to_param, :plan_cuentum => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested plan_cuentum" do
      plan_cuentum = PlanCuentum.create! valid_attributes
      expect {
        delete :destroy, {:id => plan_cuentum.to_param}, valid_session
      }.to change(PlanCuentum, :count).by(-1)
    end

    it "redirects to the plan_cuenta list" do
      plan_cuentum = PlanCuentum.create! valid_attributes
      delete :destroy, {:id => plan_cuentum.to_param}, valid_session
      expect(response).to redirect_to(plan_cuenta_url)
    end
  end

end
